[36m[2023-11-29 21:21:33 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-29 21:21:33 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-29 21:21:33 DEBUG] [cli:119][39m Using settings file '/home/dexne/.chaostoolkit/settings.yaml'
[36m[2023-11-29 21:21:35 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/dexne/.chaostoolkit/settings.yaml'.
[36m[2023-11-29 21:21:35 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 21:21:35 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 21:21:35 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 21:21:35 DEBUG] [caching:35][39m Cached 2 activities
[32m[2023-11-29 21:21:35 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-29 21:21:35 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-29 21:21:35 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-29 21:21:35 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-29 21:21:35 DEBUG] [caching:42][39m Clearing activities cache
[31m[2023-11-29 21:21:35 ERROR] [cli:278][39m could not find Python module 'chaosk8s.probes' in activity 'all-our-microservices-should-be-healthy'
[36m[2023-11-29 21:21:35 DEBUG] [cli:279][39m could not find Python module 'chaosk8s.probes' in activity 'all-our-microservices-should-be-healthy'
[36m[2023-11-29 21:22:52 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-29 21:22:52 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-29 21:22:52 DEBUG] [cli:119][39m Using settings file '/home/dexne/.chaostoolkit/settings.yaml'
[36m[2023-11-29 21:22:53 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/dexne/.chaostoolkit/settings.yaml'.
[36m[2023-11-29 21:22:53 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 21:22:53 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 21:22:53 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 21:22:53 DEBUG] [caching:35][39m Cached 2 activities
[32m[2023-11-29 21:22:53 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-29 21:22:53 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-29 21:22:53 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-29 21:22:53 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-11-29 21:22:54 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-11-29 21:22:54 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-29 21:22:54 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-11-29 21:22:54 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 21:22:54 DEBUG] [caching:35][39m Cached 2 activities
[36m[2023-11-29 21:22:54 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-29 21:22:54 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-29 21:22:54 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-29 21:22:54 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2023-11-29 21:22:54 INFO] [run:369][39m Running experiment: Do we remain available in face of pod going down?
[36m[2023-11-29 21:22:54 DEBUG] [__init__:59][39m Initializing controls
[32m[2023-11-29 21:22:54 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-11-29 21:22:54 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-11-29 21:22:54 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-29 21:22:54 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-11-29 21:22:54 INFO] [hypothesis:186][39m Steady state hypothesis: Verifying service remains healthy
[36m[2023-11-29 21:22:54 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-29 21:22:54 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-29 21:22:54 INFO] [activity:215][39m Probe: all-our-microservices-should-be-healthy
[36m[2023-11-29 21:22:54 DEBUG] [python:33][39m Activity 'all-our-microservices-should-be-healthy' loaded from '/home/dexne/.local/lib/python3.11/site-packages/chaosk8s/deployment/probes.py'
[36m[2023-11-29 21:22:54 DEBUG] [__init__:73][39m Using Kubernetes context 'default' from config '/home/dexne/.kube/config'
[36m[2023-11-29 21:22:55 DEBUG] [probes:48][39m Found 0 deployment(s) named 'boardsService' in ns 'default'
[36m[2023-11-29 21:22:55 DEBUG] [activity:294][39m Activity failed
    Traceback (most recent call last):
      File "/home/dexne/.local/lib/python3.11/site-packages/chaoslib/provider/python.py", line 56, in run_python_activity
        return func(**arguments)
               ^^^^^^^^^^^^^^^^^
      File "/home/dexne/.local/lib/python3.11/site-packages/chaosk8s/deployment/probes.py", line 56, in deployment_available_and_healthy
        raise ActivityFailed(m)
    chaoslib.exceptions.ActivityFailed: Deployment 'boardsService' was not found
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/dexne/.local/lib/python3.11/site-packages/chaoslib/activity.py", line 287, in run_activity
        result = run_python_activity(activity, configuration, secrets)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/dexne/.local/lib/python3.11/site-packages/chaoslib/provider/python.py", line 58, in run_python_activity
        raise ActivityFailed(
      File "/home/dexne/.local/lib/python3.11/site-packages/chaoslib/provider/python.py", line 56, in run_python_activity
        return func(**arguments)
               ^^^^^^^^^^^^^^^^^
      File "/home/dexne/.local/lib/python3.11/site-packages/chaosk8s/deployment/probes.py", line 56, in deployment_available_and_healthy
        raise ActivityFailed(m)
    chaoslib.exceptions.ActivityFailed: chaoslib.exceptions.ActivityFailed: Deployment 'boardsService' was not found
[31m[2023-11-29 21:22:55 ERROR] [activity:245][39m   => failed: chaoslib.exceptions.ActivityFailed: Deployment 'boardsService' was not found
[36m[2023-11-29 21:22:55 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[33m[2023-11-29 21:22:55 WARNING] [hypothesis:213][39m Probe terminated unexpectedly, so its tolerance could not be validated
[36m[2023-11-29 21:22:55 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[31m[2023-11-29 21:22:55 CRITICAL] [run:579][39m Steady state probe 'all-our-microservices-should-be-healthy' is not in the given tolerance so failing this experiment
[32m[2023-11-29 21:22:55 INFO] [run:515][39m Experiment ended with status: failed
[36m[2023-11-29 21:22:55 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-29 21:22:55 DEBUG] [__init__:98][39m Cleaning up controls
[36m[2023-11-29 21:22:55 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-29 21:25:23 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-29 21:25:23 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-29 21:25:23 DEBUG] [cli:119][39m Using settings file '/home/dexne/.chaostoolkit/settings.yaml'
[36m[2023-11-29 21:25:24 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/dexne/.chaostoolkit/settings.yaml'.
[36m[2023-11-29 21:25:24 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 21:25:24 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 21:25:24 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 21:25:24 DEBUG] [caching:35][39m Cached 2 activities
[32m[2023-11-29 21:25:24 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-29 21:25:24 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-29 21:25:24 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-29 21:25:24 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-11-29 21:25:25 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-11-29 21:25:25 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-29 21:25:25 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-11-29 21:25:25 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 21:25:25 DEBUG] [caching:35][39m Cached 2 activities
[36m[2023-11-29 21:25:25 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-29 21:25:25 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-29 21:25:25 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-29 21:25:25 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2023-11-29 21:25:25 INFO] [run:369][39m Running experiment: Do we remain available in face of pod going down?
[36m[2023-11-29 21:25:25 DEBUG] [__init__:59][39m Initializing controls
[32m[2023-11-29 21:25:25 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-11-29 21:25:25 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-11-29 21:25:25 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-29 21:25:25 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-11-29 21:25:25 INFO] [hypothesis:186][39m Steady state hypothesis: Verifying service remains healthy
[36m[2023-11-29 21:25:25 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-29 21:25:25 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-29 21:25:25 INFO] [activity:215][39m Probe: all-our-microservices-should-be-healthy
[36m[2023-11-29 21:25:25 DEBUG] [python:33][39m Activity 'all-our-microservices-should-be-healthy' loaded from '/home/dexne/.local/lib/python3.11/site-packages/chaosk8s/deployment/probes.py'
[36m[2023-11-29 21:25:25 DEBUG] [__init__:73][39m Using Kubernetes context 'default' from config '/home/dexne/.kube/config'
[36m[2023-11-29 21:25:26 DEBUG] [probes:48][39m Found 0 deployment(s) named 'boards-microservice-deployment' in ns 'default'
[36m[2023-11-29 21:25:26 DEBUG] [activity:294][39m Activity failed
    Traceback (most recent call last):
      File "/home/dexne/.local/lib/python3.11/site-packages/chaoslib/provider/python.py", line 56, in run_python_activity
        return func(**arguments)
               ^^^^^^^^^^^^^^^^^
      File "/home/dexne/.local/lib/python3.11/site-packages/chaosk8s/deployment/probes.py", line 56, in deployment_available_and_healthy
        raise ActivityFailed(m)
    chaoslib.exceptions.ActivityFailed: Deployment 'boards-microservice-deployment' was not found
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/dexne/.local/lib/python3.11/site-packages/chaoslib/activity.py", line 287, in run_activity
        result = run_python_activity(activity, configuration, secrets)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/dexne/.local/lib/python3.11/site-packages/chaoslib/provider/python.py", line 58, in run_python_activity
        raise ActivityFailed(
      File "/home/dexne/.local/lib/python3.11/site-packages/chaoslib/provider/python.py", line 56, in run_python_activity
        return func(**arguments)
               ^^^^^^^^^^^^^^^^^
      File "/home/dexne/.local/lib/python3.11/site-packages/chaosk8s/deployment/probes.py", line 56, in deployment_available_and_healthy
        raise ActivityFailed(m)
    chaoslib.exceptions.ActivityFailed: chaoslib.exceptions.ActivityFailed: Deployment 'boards-microservice-deployment' was not found
[31m[2023-11-29 21:25:26 ERROR] [activity:245][39m   => failed: chaoslib.exceptions.ActivityFailed: Deployment 'boards-microservice-deployment' was not found
[36m[2023-11-29 21:25:26 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[33m[2023-11-29 21:25:26 WARNING] [hypothesis:213][39m Probe terminated unexpectedly, so its tolerance could not be validated
[36m[2023-11-29 21:25:26 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[31m[2023-11-29 21:25:26 CRITICAL] [run:579][39m Steady state probe 'all-our-microservices-should-be-healthy' is not in the given tolerance so failing this experiment
[32m[2023-11-29 21:25:26 INFO] [run:515][39m Experiment ended with status: failed
[36m[2023-11-29 21:25:26 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-29 21:25:26 DEBUG] [__init__:98][39m Cleaning up controls
[36m[2023-11-29 21:25:26 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-29 21:26:59 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-29 21:26:59 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-29 21:26:59 DEBUG] [cli:119][39m Using settings file '/home/dexne/.chaostoolkit/settings.yaml'
[36m[2023-11-29 21:27:01 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/dexne/.chaostoolkit/settings.yaml'.
[36m[2023-11-29 21:27:01 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 21:27:01 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 21:27:01 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 21:27:01 DEBUG] [caching:35][39m Cached 2 activities
[32m[2023-11-29 21:27:01 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-29 21:27:01 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-29 21:27:01 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-29 21:27:01 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-11-29 21:27:01 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-11-29 21:27:01 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-29 21:27:01 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-11-29 21:27:01 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 21:27:01 DEBUG] [caching:35][39m Cached 2 activities
[36m[2023-11-29 21:27:01 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-29 21:27:01 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-29 21:27:01 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-29 21:27:01 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2023-11-29 21:27:01 INFO] [run:369][39m Running experiment: Do we remain available in face of pod going down?
[36m[2023-11-29 21:27:01 DEBUG] [__init__:59][39m Initializing controls
[32m[2023-11-29 21:27:01 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-11-29 21:27:01 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-11-29 21:27:01 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-29 21:27:01 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-11-29 21:27:01 INFO] [hypothesis:186][39m Steady state hypothesis: Verifying service remains healthy
[36m[2023-11-29 21:27:01 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-29 21:27:01 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-29 21:27:01 INFO] [activity:215][39m Probe: all-our-microservices-should-be-healthy
[36m[2023-11-29 21:27:01 DEBUG] [python:33][39m Activity 'all-our-microservices-should-be-healthy' loaded from '/home/dexne/.local/lib/python3.11/site-packages/chaosk8s/deployment/probes.py'
[36m[2023-11-29 21:27:01 DEBUG] [__init__:73][39m Using Kubernetes context 'default' from config '/home/dexne/.kube/config'
[36m[2023-11-29 21:27:02 DEBUG] [probes:48][39m Found 0 deployment(s) named 'boards-microservice-deployment' in ns 'default'
[36m[2023-11-29 21:27:02 DEBUG] [activity:294][39m Activity failed
    Traceback (most recent call last):
      File "/home/dexne/.local/lib/python3.11/site-packages/chaoslib/provider/python.py", line 56, in run_python_activity
        return func(**arguments)
               ^^^^^^^^^^^^^^^^^
      File "/home/dexne/.local/lib/python3.11/site-packages/chaosk8s/deployment/probes.py", line 56, in deployment_available_and_healthy
        raise ActivityFailed(m)
    chaoslib.exceptions.ActivityFailed: Deployment 'boards-microservice-deployment' was not found
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/dexne/.local/lib/python3.11/site-packages/chaoslib/activity.py", line 287, in run_activity
        result = run_python_activity(activity, configuration, secrets)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/dexne/.local/lib/python3.11/site-packages/chaoslib/provider/python.py", line 58, in run_python_activity
        raise ActivityFailed(
      File "/home/dexne/.local/lib/python3.11/site-packages/chaoslib/provider/python.py", line 56, in run_python_activity
        return func(**arguments)
               ^^^^^^^^^^^^^^^^^
      File "/home/dexne/.local/lib/python3.11/site-packages/chaosk8s/deployment/probes.py", line 56, in deployment_available_and_healthy
        raise ActivityFailed(m)
    chaoslib.exceptions.ActivityFailed: chaoslib.exceptions.ActivityFailed: Deployment 'boards-microservice-deployment' was not found
[31m[2023-11-29 21:27:02 ERROR] [activity:245][39m   => failed: chaoslib.exceptions.ActivityFailed: Deployment 'boards-microservice-deployment' was not found
[36m[2023-11-29 21:27:02 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[33m[2023-11-29 21:27:02 WARNING] [hypothesis:213][39m Probe terminated unexpectedly, so its tolerance could not be validated
[36m[2023-11-29 21:27:02 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[31m[2023-11-29 21:27:02 CRITICAL] [run:579][39m Steady state probe 'all-our-microservices-should-be-healthy' is not in the given tolerance so failing this experiment
[32m[2023-11-29 21:27:02 INFO] [run:515][39m Experiment ended with status: failed
[36m[2023-11-29 21:27:02 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-29 21:27:02 DEBUG] [__init__:98][39m Cleaning up controls
[36m[2023-11-29 21:27:02 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-29 21:31:45 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-29 21:31:45 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-29 21:31:45 DEBUG] [cli:119][39m Using settings file '/home/dexne/.chaostoolkit/settings.yaml'
[36m[2023-11-29 21:31:46 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/dexne/.chaostoolkit/settings.yaml'.
[36m[2023-11-29 21:31:46 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 21:31:46 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 21:31:46 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 21:31:46 DEBUG] [caching:35][39m Cached 2 activities
[32m[2023-11-29 21:31:46 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-29 21:31:46 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-29 21:31:46 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-29 21:31:46 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-11-29 21:31:47 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-11-29 21:31:47 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-29 21:31:47 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-11-29 21:31:47 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 21:31:47 DEBUG] [caching:35][39m Cached 2 activities
[36m[2023-11-29 21:31:47 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-29 21:31:47 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-29 21:31:47 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-29 21:31:47 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2023-11-29 21:31:47 INFO] [run:369][39m Running experiment: Do we remain available in face of pod going down?
[36m[2023-11-29 21:31:47 DEBUG] [__init__:59][39m Initializing controls
[32m[2023-11-29 21:31:47 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-11-29 21:31:47 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-11-29 21:31:47 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-29 21:31:47 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-11-29 21:31:47 INFO] [hypothesis:186][39m Steady state hypothesis: Verifying service remains healthy
[36m[2023-11-29 21:31:47 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-29 21:31:47 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-29 21:31:47 INFO] [activity:215][39m Probe: all-our-microservices-should-be-healthy
[36m[2023-11-29 21:31:47 DEBUG] [python:33][39m Activity 'all-our-microservices-should-be-healthy' loaded from '/home/dexne/.local/lib/python3.11/site-packages/chaosk8s/deployment/probes.py'
[36m[2023-11-29 21:31:47 DEBUG] [__init__:73][39m Using Kubernetes context 'default' from config '/home/dexne/.kube/config'
[36m[2023-11-29 21:31:47 DEBUG] [probes:48][39m Found 1 deployment(s) named 'boards-microservice-deployment' in ns 'default'
[36m[2023-11-29 21:31:47 DEBUG] [probes:59][39m Deployment has '1' available replicas
[36m[2023-11-29 21:31:47 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-11-29 21:31:47 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-29 21:31:47 DEBUG] [hypothesis:228][39m allowed tolerance is True
[32m[2023-11-29 21:31:47 INFO] [hypothesis:238][39m Steady state hypothesis is met!
[36m[2023-11-29 21:31:47 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[32m[2023-11-29 21:31:47 INFO] [run:677][39m Playing your experiment's method now...
[36m[2023-11-29 21:31:47 DEBUG] [__init__:445][39m No controls to apply on 'method'
[36m[2023-11-29 21:31:47 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-29 21:31:47 INFO] [activity:215][39m Action: terminate-boardsService-pod
[36m[2023-11-29 21:31:47 DEBUG] [python:33][39m Activity 'terminate-boardsService-pod' loaded from '/home/dexne/.local/lib/python3.11/site-packages/chaosk8s/pod/actions.py'
[36m[2023-11-29 21:31:47 DEBUG] [__init__:73][39m Using Kubernetes context 'default' from config '/home/dexne/.kube/config'
[36m[2023-11-29 21:31:48 DEBUG] [actions:232][39m Found 1 pods labelled 'app=boardsService' in ns default
[36m[2023-11-29 21:31:48 DEBUG] [activity:237][39m   => succeeded with '[]'
[32m[2023-11-29 21:31:48 INFO] [activity:257][39m Pausing after activity for 10s...
[36m[2023-11-29 21:31:58 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-29 21:31:58 DEBUG] [__init__:445][39m No controls to apply on 'method'
[36m[2023-11-29 21:31:58 DEBUG] [run:599][39m Running steady-state hypothesis after the method
[32m[2023-11-29 21:31:58 INFO] [hypothesis:186][39m Steady state hypothesis: Verifying service remains healthy
[36m[2023-11-29 21:31:58 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-29 21:31:58 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-29 21:31:58 INFO] [activity:215][39m Probe: all-our-microservices-should-be-healthy
[36m[2023-11-29 21:31:58 DEBUG] [python:33][39m Activity 'all-our-microservices-should-be-healthy' loaded from '/home/dexne/.local/lib/python3.11/site-packages/chaosk8s/deployment/probes.py'
[36m[2023-11-29 21:31:58 DEBUG] [__init__:73][39m Using Kubernetes context 'default' from config '/home/dexne/.kube/config'
[36m[2023-11-29 21:31:58 DEBUG] [probes:48][39m Found 1 deployment(s) named 'boards-microservice-deployment' in ns 'default'
[36m[2023-11-29 21:31:58 DEBUG] [probes:59][39m Deployment has '1' available replicas
[36m[2023-11-29 21:31:58 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-11-29 21:31:58 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-29 21:31:58 DEBUG] [hypothesis:228][39m allowed tolerance is True
[32m[2023-11-29 21:31:58 INFO] [hypothesis:238][39m Steady state hypothesis is met!
[36m[2023-11-29 21:31:58 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[32m[2023-11-29 21:31:58 INFO] [run:966][39m Let's rollback...
[36m[2023-11-29 21:31:58 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-29 21:31:58 INFO] [rollback:32][39m No declared rollbacks, let's move on.
[36m[2023-11-29 21:31:58 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-29 21:31:58 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-11-29 21:31:58 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-29 21:31:58 DEBUG] [__init__:98][39m Cleaning up controls
[36m[2023-11-29 21:31:58 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-29 22:16:01 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-29 22:16:01 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-29 22:16:01 DEBUG] [cli:119][39m Using settings file '/home/dexne/.chaostoolkit/settings.yaml'
[36m[2023-11-29 22:16:02 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/dexne/.chaostoolkit/settings.yaml'.
[36m[2023-11-29 22:16:02 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 22:16:02 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 22:16:02 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 22:16:02 DEBUG] [caching:35][39m Cached 2 activities
[32m[2023-11-29 22:16:02 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-29 22:16:02 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-29 22:16:02 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-29 22:16:02 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-11-29 22:16:03 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-11-29 22:16:03 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-29 22:16:03 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-11-29 22:16:03 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 22:16:03 DEBUG] [caching:35][39m Cached 2 activities
[36m[2023-11-29 22:16:03 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-29 22:16:03 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-29 22:16:03 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-29 22:16:03 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2023-11-29 22:16:03 INFO] [run:369][39m Running experiment: Do we remain available in face of pod going down?
[36m[2023-11-29 22:16:03 DEBUG] [__init__:59][39m Initializing controls
[32m[2023-11-29 22:16:03 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-11-29 22:16:03 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-11-29 22:16:03 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-29 22:16:03 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-11-29 22:16:03 INFO] [hypothesis:186][39m Steady state hypothesis: Verifying service remains healthy
[36m[2023-11-29 22:16:03 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-29 22:16:03 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-29 22:16:03 INFO] [activity:215][39m Probe: all-our-microservices-should-be-healthy
[36m[2023-11-29 22:16:03 DEBUG] [python:33][39m Activity 'all-our-microservices-should-be-healthy' loaded from '/home/dexne/.local/lib/python3.11/site-packages/chaosk8s/deployment/probes.py'
[36m[2023-11-29 22:16:03 DEBUG] [__init__:73][39m Using Kubernetes context 'default' from config '/home/dexne/.kube/config'
[36m[2023-11-29 22:16:04 DEBUG] [probes:48][39m Found 1 deployment(s) named 'boards-microservice-deployment' in ns 'default'
[36m[2023-11-29 22:16:04 DEBUG] [probes:59][39m Deployment has '1' available replicas
[36m[2023-11-29 22:16:04 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-11-29 22:16:04 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-29 22:16:04 DEBUG] [hypothesis:228][39m allowed tolerance is True
[32m[2023-11-29 22:16:04 INFO] [hypothesis:238][39m Steady state hypothesis is met!
[36m[2023-11-29 22:16:04 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[32m[2023-11-29 22:16:04 INFO] [run:677][39m Playing your experiment's method now...
[36m[2023-11-29 22:16:04 DEBUG] [__init__:445][39m No controls to apply on 'method'
[36m[2023-11-29 22:16:04 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-29 22:16:04 INFO] [activity:215][39m Action: terminate-boardsService-pod
[36m[2023-11-29 22:16:04 DEBUG] [python:33][39m Activity 'terminate-boardsService-pod' loaded from '/home/dexne/.local/lib/python3.11/site-packages/chaosk8s/pod/actions.py'
[36m[2023-11-29 22:16:04 DEBUG] [__init__:73][39m Using Kubernetes context 'default' from config '/home/dexne/.kube/config'
[36m[2023-11-29 22:16:04 DEBUG] [actions:232][39m Found 1 pods labelled 'app=boardsService' in ns default
[36m[2023-11-29 22:16:04 DEBUG] [activity:237][39m   => succeeded with '[]'
[32m[2023-11-29 22:16:04 INFO] [activity:257][39m Pausing after activity for 10s...
[36m[2023-11-29 22:16:14 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-29 22:16:14 DEBUG] [__init__:445][39m No controls to apply on 'method'
[36m[2023-11-29 22:16:14 DEBUG] [run:599][39m Running steady-state hypothesis after the method
[32m[2023-11-29 22:16:14 INFO] [hypothesis:186][39m Steady state hypothesis: Verifying service remains healthy
[36m[2023-11-29 22:16:14 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-29 22:16:14 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-29 22:16:14 INFO] [activity:215][39m Probe: all-our-microservices-should-be-healthy
[36m[2023-11-29 22:16:14 DEBUG] [python:33][39m Activity 'all-our-microservices-should-be-healthy' loaded from '/home/dexne/.local/lib/python3.11/site-packages/chaosk8s/deployment/probes.py'
[36m[2023-11-29 22:16:14 DEBUG] [__init__:73][39m Using Kubernetes context 'default' from config '/home/dexne/.kube/config'
[36m[2023-11-29 22:16:14 DEBUG] [probes:48][39m Found 1 deployment(s) named 'boards-microservice-deployment' in ns 'default'
[36m[2023-11-29 22:16:14 DEBUG] [probes:59][39m Deployment has '1' available replicas
[36m[2023-11-29 22:16:14 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-11-29 22:16:14 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-29 22:16:14 DEBUG] [hypothesis:228][39m allowed tolerance is True
[32m[2023-11-29 22:16:14 INFO] [hypothesis:238][39m Steady state hypothesis is met!
[36m[2023-11-29 22:16:14 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[32m[2023-11-29 22:16:14 INFO] [run:966][39m Let's rollback...
[36m[2023-11-29 22:16:14 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-29 22:16:14 INFO] [rollback:32][39m No declared rollbacks, let's move on.
[36m[2023-11-29 22:16:14 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-29 22:16:14 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-11-29 22:16:14 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-29 22:16:14 DEBUG] [__init__:98][39m Cleaning up controls
[36m[2023-11-29 22:16:14 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-29 22:18:00 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-29 22:18:00 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-29 22:18:00 DEBUG] [cli:119][39m Using settings file '/home/dexne/.chaostoolkit/settings.yaml'
[36m[2023-11-29 22:18:01 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/dexne/.chaostoolkit/settings.yaml'.
[36m[2023-11-29 22:18:01 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 22:18:01 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 22:18:01 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 22:18:01 DEBUG] [caching:35][39m Cached 2 activities
[32m[2023-11-29 22:18:01 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-29 22:18:01 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-29 22:18:01 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-29 22:18:01 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-11-29 22:18:01 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-11-29 22:18:01 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-29 22:18:01 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-11-29 22:18:01 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 22:18:01 DEBUG] [caching:35][39m Cached 2 activities
[36m[2023-11-29 22:18:01 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-29 22:18:01 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-29 22:18:01 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-29 22:18:01 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2023-11-29 22:18:01 INFO] [run:369][39m Running experiment: Do we remain available in face of pod going down?
[36m[2023-11-29 22:18:01 DEBUG] [__init__:59][39m Initializing controls
[32m[2023-11-29 22:18:01 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-11-29 22:18:01 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-11-29 22:18:01 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-29 22:18:01 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-11-29 22:18:01 INFO] [hypothesis:186][39m Steady state hypothesis: Verifying service remains healthy
[36m[2023-11-29 22:18:01 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-29 22:18:01 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-29 22:18:01 INFO] [activity:215][39m Probe: all-our-microservices-should-be-healthy
[36m[2023-11-29 22:18:01 DEBUG] [python:33][39m Activity 'all-our-microservices-should-be-healthy' loaded from '/home/dexne/.local/lib/python3.11/site-packages/chaosk8s/deployment/probes.py'
[36m[2023-11-29 22:18:01 DEBUG] [__init__:73][39m Using Kubernetes context 'default' from config '/home/dexne/.kube/config'
[36m[2023-11-29 22:18:06 DEBUG] [probes:48][39m Found 1 deployment(s) named 'boards-microservice-deployment' in ns 'default'
[36m[2023-11-29 22:18:06 DEBUG] [probes:59][39m Deployment has '1' available replicas
[36m[2023-11-29 22:18:06 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-11-29 22:18:06 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-29 22:18:06 DEBUG] [hypothesis:228][39m allowed tolerance is True
[32m[2023-11-29 22:18:06 INFO] [hypothesis:238][39m Steady state hypothesis is met!
[36m[2023-11-29 22:18:06 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[32m[2023-11-29 22:18:06 INFO] [run:677][39m Playing your experiment's method now...
[36m[2023-11-29 22:18:06 DEBUG] [__init__:445][39m No controls to apply on 'method'
[36m[2023-11-29 22:18:06 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-29 22:18:06 INFO] [activity:215][39m Action: terminate-boardsService-pod
[36m[2023-11-29 22:18:06 DEBUG] [python:33][39m Activity 'terminate-boardsService-pod' loaded from '/home/dexne/.local/lib/python3.11/site-packages/chaosk8s/pod/actions.py'
[36m[2023-11-29 22:18:06 DEBUG] [__init__:73][39m Using Kubernetes context 'default' from config '/home/dexne/.kube/config'
[36m[2023-11-29 22:18:06 DEBUG] [actions:232][39m Found 1 pods labelled 'app=boardsService' in ns default
[36m[2023-11-29 22:18:06 DEBUG] [activity:237][39m   => succeeded with '[]'
[32m[2023-11-29 22:18:06 INFO] [activity:257][39m Pausing after activity for 10s...
[36m[2023-11-29 22:18:16 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-29 22:18:16 DEBUG] [__init__:445][39m No controls to apply on 'method'
[36m[2023-11-29 22:18:16 DEBUG] [run:599][39m Running steady-state hypothesis after the method
[32m[2023-11-29 22:18:16 INFO] [hypothesis:186][39m Steady state hypothesis: Verifying service remains healthy
[36m[2023-11-29 22:18:16 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-29 22:18:16 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-29 22:18:16 INFO] [activity:215][39m Probe: all-our-microservices-should-be-healthy
[36m[2023-11-29 22:18:16 DEBUG] [python:33][39m Activity 'all-our-microservices-should-be-healthy' loaded from '/home/dexne/.local/lib/python3.11/site-packages/chaosk8s/deployment/probes.py'
[36m[2023-11-29 22:18:16 DEBUG] [__init__:73][39m Using Kubernetes context 'default' from config '/home/dexne/.kube/config'
[36m[2023-11-29 22:18:17 DEBUG] [probes:48][39m Found 1 deployment(s) named 'boards-microservice-deployment' in ns 'default'
[36m[2023-11-29 22:18:17 DEBUG] [probes:59][39m Deployment has '1' available replicas
[36m[2023-11-29 22:18:17 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-11-29 22:18:17 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-29 22:18:17 DEBUG] [hypothesis:228][39m allowed tolerance is True
[32m[2023-11-29 22:18:17 INFO] [hypothesis:238][39m Steady state hypothesis is met!
[36m[2023-11-29 22:18:17 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[32m[2023-11-29 22:18:17 INFO] [run:966][39m Let's rollback...
[36m[2023-11-29 22:18:17 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-29 22:18:17 INFO] [rollback:32][39m No declared rollbacks, let's move on.
[36m[2023-11-29 22:18:17 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-29 22:18:17 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-11-29 22:18:17 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-29 22:18:17 DEBUG] [__init__:98][39m Cleaning up controls
[36m[2023-11-29 22:18:17 DEBUG] [caching:42][39m Clearing activities cache
